sudo: required
services:
  - docker

before_install:
  - docker build -t alexg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexg/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-central-1-685180409254"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access+key: "$AWS_SECRET_KEY"