sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t alexg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexg/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-travis"
  env: "docker-travis-env"
  bucket_name: "elasticbeanstalk-eu-central-1-685180409254"
  bucket_path: "docker-travis"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
